version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbchat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: serve

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/dbchat
      SECRET_KEY: your-secret-key-here
      API_BASE_URL: http://localhost:8000
      OLLAMA_ENDPOINT: http://ollama:11434
      OLLAMA_MODEL: llama3.2
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 & 
             streamlit run app/frontend.py --server.port 8501 --server.address 0.0.0.0"

volumes:
  postgres_data:
  ollama_data: 